name = "dbda-r-cloudflare"
compatibility_date = "2026-09-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "dbda-db"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
